

num_rounds: 10
num_clients: 100
batch_size: 20
num_classes: 10
num_clients_per_round_fit: 10
num_clients_per_round_eval: 25
config_fit:
  lr: 0.01
  momentum: 0.9
  local_epochs: 1
num_cpus: 1
num_gpus: 0.0
fraction_fit: 0.1
fraction_evaluate: 0.1